# Generated by Django 3.0.5 on 2020-05-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlighter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabelTypes',
            new_name='LabelType',
        ),
        migrations.RenameField(
            model_name='summaryentry',
            old_name='publications',
            new_name='labels',
        ),
    ]
