# Generated by Django 3.0.5 on 2020-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlighter', '0002_auto_20200502_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryentry',
            name='processed',
            field=models.TextField(default='old text'),
            preserve_default=False,
        ),
    ]
